name: web

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Flutter を安定版でセットアップ（ここが肝）
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: 'stable'   # 固定したいなら 3.22.2 など具体値でもOK

      - name: Enable web
        run: flutter config --enable-web

      - name: Get dependencies
        run: flutter pub get

      # web-renderer でコケていたので一旦省略（必要ならコメントの行に差し替え）
      - name: Build web
        run: flutter build web --release --base-href "/roulette/"
        # もし renderer を指定したいときは下を使う（Flutter が十分新しければOK）
        # run: flutter build web --release --web-renderer html --base-href "/roulette/"

      # gh-pages ブランチへ出力をデプロイ
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          force_orphan: true
